// <auto-generated />
namespace ticket_without_mail.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class resolver : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(resolver));
        
        string IMigrationMetadata.Id
        {
            get { return "202107221155125_resolver"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
